# Test

name: Test

on:
  push

jobs:
  test00:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Run
      run: |
        cd js/Map
        nodejs test.js
